#!/usr/bin/env bash
# build.sh — Vercel 构建时注入环境变量到 config.js
# 供 vercel.json -> buildCommand 调用

set -e

# 读取 Vercel 环境变量（构建时注入）
# 变量名：NEXT_PUBLIC_ADVER_ENABLE（与 craftisle-app 保持一致）
AD_ENABLED="${NEXT_PUBLIC_ADVER_ENABLE:-false}"

# 生成 config.js（被 HTML 同步加载，在 monetag.js 之前执行）
cat > config.js << EOF
// Auto-generated by build.sh — DO NOT EDIT
// 广告总开关：由 Vercel 环境变量 NEXT_PUBLIC_ADVER_ENABLE 控制
window.ADVER_ENABLE = "${AD_ENABLED}";
EOF

echo "[build] config.js generated: ADVER_ENABLE=${AD_ENABLED}"
echo "[build] done"
